### ISSUE TITLE
Latest Version doesn't work with Rails < 2.3.7

### ISSUE THREAD

**Issue by skaczor** [weppos/tabs_on_rails#5]
NoMethodError - undefined method `html_safe' for "&lt;/ul&gt;":String

<pre>
tabs_on_rails-1.3.1/lib/tabs_on_rails/tabs/tabs_builder.rb:85:in `try'
tabs_on_rails-1.3.1/lib/tabs_on_rails/tabs/tabs_builder.rb:85:in `close_tabs'
tabs_on_rails-1.3.1/lib/tabs_on_rails/tabs.rb:41:in `call'
tabs_on_rails-1.3.1/lib/tabs_on_rails/tabs.rb:41:in `close_tabs'
tabs_on_rails-1.3.1/lib/tabs_on_rails/tabs.rb:60:in `render'
tabs_on_rails-1.3.1/lib/tabs_on_rails/controller_mixin.rb:205:in `tabs_tag'
</pre>
